import http from './http';
export const adminYears = () => http.get('/admin/reimbursement-years');
export const initYear = (data) => http.post('/admin/reimbursement-years/initialize', data);
export const updateYear = (id, data) => http.put(`/admin/reimbursement-years/${id}`, data);
export const deleteYear = (id) => http.delete(`/admin/reimbursement-years/${id}`);
export const activateYear = (id) => http.post(`/admin/reimbursement-years/${id}/activate`);
export const closeYear = (id) => http.post(`/admin/reimbursement-years/${id}/close`);
export const categories = () => http.get('/admin/reimbursement-categories');
export const createCategory = (data) => http.post('/admin/reimbursement-categories', data);
export const updateCategory = (id, data) => http.put(`/admin/reimbursement-categories/${id}`, data);
export const deleteCategory = (id) => http.delete(`/admin/reimbursement-categories/${id}`);
export const createType = (data) => http.post('/admin/reimbursement-types', data);
export const updateType = (id, data) => http.put(`/admin/reimbursement-types/${id}`, data);
export const deleteType = (id) => http.delete(`/admin/reimbursement-types/${id}`);
export const employees = (params) => http.get('/admin/employees', { params });
export const createEmployee = (data) => http.post('/admin/employees', data);
export const updateEmployee = (id, data) => http.put(`/admin/employees/${id}`, data);
export const deleteEmployee = (id) => http.delete(`/admin/employees/${id}`);
export const enableEmployee = (id) => http.post(`/admin/employees/${id}/enable`);
export const importEmployees = (form) => http.post('/admin/employees/import', form, { headers: { 'Content-Type': 'multipart/form-data' } });
export const children = (employeeId) => http.get(`/admin/employees/${employeeId}/children`);
export const createChild = (employeeId, data) => http.post(`/admin/employees/${employeeId}/children`, data);
export const updateChild = (id, data) => http.put(`/admin/children/${id}`, data);
export const deleteChild = (id, data) => http.delete(`/admin/children/${id}`, { data });
export const enableChild = (id) => http.post(`/admin/children/${id}/enable`);
export const users = () => http.get('/admin/users');
export const createUser = (data) => http.post('/admin/users', data);
export const updateUser = (id, data) => http.put(`/admin/users/${id}`, data);
export const resetPassword = (id, data) => http.post(`/admin/users/${id}/reset-password`, data);
export const enableUser = (id) => http.post(`/admin/users/${id}/enable`);
export const disableUser = (id) => http.post(`/admin/users/${id}/disable`);
export const getParameters = () => http.get('/admin/system-parameters');
export const updateParameters = (data) => http.put('/admin/system-parameters', data);
