<template><MainLayout><div class="page-card"><div class="toolbar"><h3 style="margin:0">账号管理</h3><a-button type="primary" @click="openCreate">新增账号</a-button></div><a-table :data="items"><template #columns><a-table-column title="用户名" data-index="username"/><a-table-column title="角色" data-index="role_code"/><a-table-column title="绑定员工"><template #cell="{record}">{{employeeLabel(record.employee_id)}}</template></a-table-column><a-table-column title="状态"><template #cell="{record}">{{record.enabled?'启用':'停用'}}</template></a-table-column><a-table-column title="首次改密"><template #cell="{record}">{{record.must_change_password?'是':'否'}}</template></a-table-column><a-table-column title="操作"><template #cell="{record}"><a-button size="small" @click="openEdit(record)">编辑</a-button><a-button size="small" @click="reset(record)">重置密码</a-button><a-button size="small" :status="record.enabled?'danger':'success'" @click="toggle(record)">{{record.enabled?'停用':'启用'}}</a-button></template></a-table-column></template></a-table><a-modal v-model:visible="visible" title="账号" @ok="save"><a-form :model="form"><a-form-item label="用户名"><a-input v-model="form.username" :disabled="!!form.id"/></a-form-item><a-form-item label="角色"><a-select v-model="form.roleCode" @change="roleChanged"><a-option value="EMPLOYEE">员工</a-option><a-option value="HR">HR</a-option><a-option value="FINANCE">财务</a-option><a-option value="ADMIN">管理员</a-option></a-select></a-form-item><a-form-item v-if="form.roleCode==='EMPLOYEE'" label="绑定员工"><a-select v-model="form.employeeId" allow-search placeholder="工号 / 姓名"><a-option v-for="e in employeeOptions" :key="e.id" :value="e.id">{{e.employee_no}} - {{e.name}}</a-option></a-select></a-form-item><a-form-item v-else label="员工绑定"><a-input value="非员工角色无需绑定" disabled/></a-form-item><a-form-item v-if="!form.id" label="初始密码"><a-input-password v-model="form.password" placeholder="至少8位，含大写、小写、数字"/><div class="form-help">密码至少8位，必须同时包含大写字母、小写字母和数字。</div></a-form-item></a-form></a-modal></div></MainLayout></template>
<script setup>
import {ref,onMounted,reactive} from 'vue';import {Message} from '@arco-design/web-vue';import MainLayout from '../layouts/MainLayout.vue';import {users,createUser,updateUser,resetPassword,enableUser,disableUser,employees} from '../api/admin';
const items=ref([]),employeeOptions=ref([]),visible=ref(false);const form=reactive({id:null,username:'',roleCode:'EMPLOYEE',employeeId:null,password:''});const error=e=>Message.error({content:e.message||'操作失败',duration:5000});
const load=async()=>{try{const [u,e]=await Promise.all([users(),employees({page:1,pageSize:1000})]);items.value=u.data;employeeOptions.value=e.data.items}catch(e){error(e)}};const employeeLabel=id=>{const e=employeeOptions.value.find(x=>x.id===id);return e?`${e.employee_no} - ${e.name}`:(id?`员工ID ${id}`:'未绑定')};
const openCreate=()=>{Object.assign(form,{id:null,username:'',roleCode:'EMPLOYEE',employeeId:null,password:''});visible.value=true};const openEdit=r=>{Object.assign(form,{id:r.id,username:r.username,roleCode:r.role_code,employeeId:r.employee_id,password:''});visible.value=true};const roleChanged=()=>{if(form.roleCode!=='EMPLOYEE')form.employeeId=null};
const save=async()=>{try{if(!form.username.trim())throw new Error('用户名不能为空');if(form.roleCode==='EMPLOYEE'&&!form.employeeId)throw new Error('员工角色必须绑定员工主数据，请选择员工');if(!form.id){if(!form.password)throw new Error('初始密码不能为空');if(form.password.length<8||!/[A-Z]/.test(form.password)||!/[a-z]/.test(form.password)||!/\d/.test(form.password))throw new Error('密码至少8位，且必须同时包含大写字母、小写字母和数字')}if(form.id)await updateUser(form.id,{roleCode:form.roleCode,employeeId:form.employeeId});else await createUser({username:form.username.trim(),roleCode:form.roleCode,employeeId:form.employeeId,password:form.password});visible.value=false;Message.success('账号已保存');load()}catch(e){error(e)}};
const reset=async r=>{const pwd=window.prompt('请输入新密码（至少8位，含大写、小写、数字）');if(!pwd)return;try{if(pwd.length<8||!/[A-Z]/.test(pwd)||!/[a-z]/.test(pwd)||!/\d/.test(pwd))throw new Error('密码至少8位，且必须同时包含大写字母、小写字母和数字');await resetPassword(r.id,{password:pwd});Message.success('密码已重置')}catch(e){error(e)}};const toggle=async r=>{try{if(r.enabled)await disableUser(r.id);else await enableUser(r.id);load()}catch(e){error(e)}};onMounted(load);
</script>
<style scoped>.form-help{font-size:12px;color:#86909c;margin-top:4px}</style>
