<template>
<MainLayout><div class="page-card">
  <div class="toolbar"><h3 style="margin:0">报销分类 / 类型 / 比例</h3><a-button type="primary" @click="openCategory">新增分类</a-button><a-button @click="openType">新增类型</a-button></div>
  <a-table :data="rows"><template #columns>
    <a-table-column title="分类"><template #cell="{record}">{{record.categoryName}}</template></a-table-column>
    <a-table-column title="类型" data-index="name"/><a-table-column title="编码" data-index="code"/><a-table-column title="比例"><template #cell="{record}">{{Math.round(record.reimbursementRate*100)}}%</template></a-table-column>
    <a-table-column title="操作"><template #cell="{record}"><a-button size="small" @click="openType(record)">编辑</a-button><a-popconfirm content="确认停用该类型？" @ok="removeType(record)"><a-button size="small" status="danger">停用</a-button></a-popconfirm></template></a-table-column>
  </template></a-table>
  <a-alert style="margin-top:12px" type="info">报销比例为长期固定业务参数，不按年度设置；历史报销明细保存实际采用的比例快照。</a-alert>
  <a-modal v-model:visible="catVisible" title="报销分类" @ok="saveCategory"><a-form :model="catForm"><a-form-item label="编码"><a-input v-model="catForm.code"/></a-form-item><a-form-item label="名称"><a-input v-model="catForm.name"/></a-form-item><a-form-item label="排序"><a-input-number v-model="catForm.sortNo"/></a-form-item></a-form></a-modal>
  <a-modal v-model:visible="typeVisible" title="报销类型" @ok="saveType"><a-form :model="typeForm"><a-form-item label="分类"><a-select v-model="typeForm.categoryId"><a-option v-for="c in cats" :key="c.id" :value="c.id">{{c.name}}</a-option></a-select></a-form-item><a-form-item label="编码"><a-input v-model="typeForm.code" :disabled="!!typeForm.id"/></a-form-item><a-form-item label="名称"><a-input v-model="typeForm.name"/></a-form-item><a-form-item label="比例"><a-input-number v-model="typeForm.reimbursementRate" :min="0.0001" :max="1" :step="0.01"/></a-form-item><a-form-item label="排序"><a-input-number v-model="typeForm.sortNo"/></a-form-item></a-form></a-modal>
</div></MainLayout></template>
<script setup>
import {ref,onMounted,reactive} from 'vue';import {Message} from '@arco-design/web-vue';import MainLayout from '../layouts/MainLayout.vue';import {categories,createCategory,createType,updateType,deleteType} from '../api/admin';const cats=ref([]),rows=ref([]),catVisible=ref(false),typeVisible=ref(false);const catForm=reactive({code:'',name:'',sortNo:1});const typeForm=reactive({id:null,categoryId:null,code:'',name:'',reimbursementRate:.8,sortNo:1});const load=async()=>{const r=await categories();cats.value=r.data;rows.value=r.data.flatMap(c=>c.types.map(t=>({...t,categoryName:c.name,categoryId:c.id})));};const openCategory=()=>{Object.assign(catForm,{code:'',name:'',sortNo:1});catVisible.value=true};const openType=(r=null)=>{Object.assign(typeForm,r?{id:r.id,categoryId:r.categoryId,code:r.code,name:r.name,reimbursementRate:r.reimbursementRate,sortNo:r.sortNo||1}:{id:null,categoryId:cats.value[0]?.id,code:'',name:'',reimbursementRate:.8,sortNo:1});typeVisible.value=true};const saveCategory=async()=>{try{if(!catForm.code.trim())throw new Error('分类编码不能为空');if(!catForm.name.trim())throw new Error('分类名称不能为空');await createCategory(catForm);catVisible.value=false;Message.success('分类已保存');load()}catch(e){Message.error(e.message||'保存失败')}};const saveType=async()=>{try{if(!typeForm.categoryId)throw new Error('请选择报销分类');if(!typeForm.code.trim())throw new Error('报销类型编码不能为空');if(!typeForm.name.trim())throw new Error('报销类型名称不能为空');if(Number(typeForm.reimbursementRate)<=0||Number(typeForm.reimbursementRate)>1)throw new Error('报销比例必须大于0且不超过1，例如80%请填写0.8');if(typeForm.id) await updateType(typeForm.id,typeForm);else await createType(typeForm);typeVisible.value=false;Message.success('报销类型已保存');load()}catch(e){Message.error(e.message||'保存失败')}};const removeType=async(r)=>{await deleteType(r.id);Message.success('已停用');load()};onMounted(load);
</script>
